// NOTICE: This file is generated by scripts/make_country_data.py! Do not modify!

// Imports
import flag_AD from "../../assets/img/countries/AD.svg";
import flag_AE from "../../assets/img/countries/AE.svg";
import flag_AF from "../../assets/img/countries/AF.svg";
import flag_AG from "../../assets/img/countries/AG.svg";
import flag_AI from "../../assets/img/countries/AI.svg";
import flag_AL from "../../assets/img/countries/AL.svg";
import flag_AM from "../../assets/img/countries/AM.svg";
import flag_AO from "../../assets/img/countries/AO.svg";
import flag_AQ from "../../assets/img/countries/AQ.svg";
import flag_AR from "../../assets/img/countries/AR.svg";
import flag_AS from "../../assets/img/countries/AS.svg";
import flag_AT from "../../assets/img/countries/AT.svg";
import flag_AU from "../../assets/img/countries/AU.svg";
import flag_AZ from "../../assets/img/countries/AZ.svg";
import flag_BA from "../../assets/img/countries/BA.svg";
import flag_BB from "../../assets/img/countries/BB.svg";
import flag_BD from "../../assets/img/countries/BD.svg";
import flag_BE from "../../assets/img/countries/BE.svg";
import flag_BF from "../../assets/img/countries/BF.svg";
import flag_BG from "../../assets/img/countries/BG.svg";
import flag_BH from "../../assets/img/countries/BH.svg";
import flag_BI from "../../assets/img/countries/BI.svg";
import flag_BJ from "../../assets/img/countries/BJ.svg";
import flag_BM from "../../assets/img/countries/BM.svg";
import flag_BN from "../../assets/img/countries/BN.svg";
import flag_BO from "../../assets/img/countries/BO.svg";
import flag_BQ from "../../assets/img/countries/BQ.svg";
import flag_BR from "../../assets/img/countries/BR.svg";
import flag_BS from "../../assets/img/countries/BS.svg";
import flag_BT from "../../assets/img/countries/BT.svg";
import flag_BW from "../../assets/img/countries/BW.svg";
import flag_BY from "../../assets/img/countries/BY.svg";
import flag_BZ from "../../assets/img/countries/BZ.svg";
import flag_CA from "../../assets/img/countries/CA.svg";
import flag_CD from "../../assets/img/countries/CD.svg";
import flag_CF from "../../assets/img/countries/CF.svg";
import flag_CG from "../../assets/img/countries/CG.svg";
import flag_CH from "../../assets/img/countries/CH.svg";
import flag_CI from "../../assets/img/countries/CI.svg";
import flag_CK from "../../assets/img/countries/CK.svg";
import flag_CL from "../../assets/img/countries/CL.svg";
import flag_CM from "../../assets/img/countries/CM.svg";
import flag_CN from "../../assets/img/countries/CN.svg";
import flag_CO from "../../assets/img/countries/CO.svg";
import flag_CR from "../../assets/img/countries/CR.svg";
import flag_CU from "../../assets/img/countries/CU.svg";
import flag_CV from "../../assets/img/countries/CV.svg";
import flag_CY from "../../assets/img/countries/CY.svg";
import flag_CZ from "../../assets/img/countries/CZ.svg";
import flag_DE from "../../assets/img/countries/DE.svg";
import flag_DJ from "../../assets/img/countries/DJ.svg";
import flag_DK from "../../assets/img/countries/DK.svg";
import flag_DM from "../../assets/img/countries/DM.svg";
import flag_DO from "../../assets/img/countries/DO.svg";
import flag_DZ from "../../assets/img/countries/DZ.svg";
import flag_EC from "../../assets/img/countries/EC.svg";
import flag_EE from "../../assets/img/countries/EE.svg";
import flag_EG from "../../assets/img/countries/EG.svg";
import flag_ER from "../../assets/img/countries/ER.svg";
import flag_ES from "../../assets/img/countries/ES.svg";
import flag_ET from "../../assets/img/countries/ET.svg";
import flag_FI from "../../assets/img/countries/FI.svg";
import flag_FJ from "../../assets/img/countries/FJ.svg";
import flag_FK from "../../assets/img/countries/FK.svg";
import flag_FM from "../../assets/img/countries/FM.svg";
import flag_FO from "../../assets/img/countries/FO.svg";
import flag_FR from "../../assets/img/countries/FR.svg";
import flag_GA from "../../assets/img/countries/GA.svg";
import flag_GB from "../../assets/img/countries/GB.svg";
import flag_GD from "../../assets/img/countries/GD.svg";
import flag_GE from "../../assets/img/countries/GE.svg";
import flag_GF from "../../assets/img/countries/GF.svg";
import flag_GG from "../../assets/img/countries/GG.svg";
import flag_GH from "../../assets/img/countries/GH.svg";
import flag_GI from "../../assets/img/countries/GI.svg";
import flag_GL from "../../assets/img/countries/GL.svg";
import flag_GM from "../../assets/img/countries/GM.svg";
import flag_GN from "../../assets/img/countries/GN.svg";
import flag_GP from "../../assets/img/countries/GP.svg";
import flag_GQ from "../../assets/img/countries/GQ.svg";
import flag_GR from "../../assets/img/countries/GR.svg";
import flag_GS from "../../assets/img/countries/GS.svg";
import flag_GT from "../../assets/img/countries/GT.svg";
import flag_GU from "../../assets/img/countries/GU.svg";
import flag_GW from "../../assets/img/countries/GW.svg";
import flag_GY from "../../assets/img/countries/GY.svg";
import flag_HK from "../../assets/img/countries/HK.svg";
import flag_HN from "../../assets/img/countries/HN.svg";
import flag_HR from "../../assets/img/countries/HR.svg";
import flag_HT from "../../assets/img/countries/HT.svg";
import flag_HU from "../../assets/img/countries/HU.svg";
import flag_ID from "../../assets/img/countries/ID.svg";
import flag_IE from "../../assets/img/countries/IE.svg";
import flag_IL from "../../assets/img/countries/IL.svg";
import flag_IM from "../../assets/img/countries/IM.svg";
import flag_IN from "../../assets/img/countries/IN.svg";
import flag_IO from "../../assets/img/countries/IO.svg";
import flag_IQ from "../../assets/img/countries/IQ.svg";
import flag_IR from "../../assets/img/countries/IR.svg";
import flag_IS from "../../assets/img/countries/IS.svg";
import flag_IT from "../../assets/img/countries/IT.svg";
import flag_JE from "../../assets/img/countries/JE.svg";
import flag_JM from "../../assets/img/countries/JM.svg";
import flag_JO from "../../assets/img/countries/JO.svg";
import flag_JP from "../../assets/img/countries/JP.svg";
import flag_KE from "../../assets/img/countries/KE.svg";
import flag_KG from "../../assets/img/countries/KG.svg";
import flag_KH from "../../assets/img/countries/KH.svg";
import flag_KI from "../../assets/img/countries/KI.svg";
import flag_KM from "../../assets/img/countries/KM.svg";
import flag_KN from "../../assets/img/countries/KN.svg";
import flag_KP from "../../assets/img/countries/KP.svg";
import flag_KR from "../../assets/img/countries/KR.svg";
import flag_KW from "../../assets/img/countries/KW.svg";
import flag_KY from "../../assets/img/countries/KY.svg";
import flag_KZ from "../../assets/img/countries/KZ.svg";
import flag_LA from "../../assets/img/countries/LA.svg";
import flag_LB from "../../assets/img/countries/LB.svg";
import flag_LC from "../../assets/img/countries/LC.svg";
import flag_LI from "../../assets/img/countries/LI.svg";
import flag_LK from "../../assets/img/countries/LK.svg";
import flag_LR from "../../assets/img/countries/LR.svg";
import flag_LS from "../../assets/img/countries/LS.svg";
import flag_LT from "../../assets/img/countries/LT.svg";
import flag_LU from "../../assets/img/countries/LU.svg";
import flag_LV from "../../assets/img/countries/LV.svg";
import flag_LY from "../../assets/img/countries/LY.svg";
import flag_MA from "../../assets/img/countries/MA.svg";
import flag_MC from "../../assets/img/countries/MC.svg";
import flag_MD from "../../assets/img/countries/MD.svg";
import flag_ME from "../../assets/img/countries/ME.svg";
import flag_MG from "../../assets/img/countries/MG.svg";
import flag_MH from "../../assets/img/countries/MH.svg";
import flag_MK from "../../assets/img/countries/MK.svg";
import flag_ML from "../../assets/img/countries/ML.svg";
import flag_MM from "../../assets/img/countries/MM.svg";
import flag_MN from "../../assets/img/countries/MN.svg";
import flag_MO from "../../assets/img/countries/MO.svg";
import flag_MP from "../../assets/img/countries/MP.svg";
import flag_MQ from "../../assets/img/countries/MQ.svg";
import flag_MR from "../../assets/img/countries/MR.svg";
import flag_MS from "../../assets/img/countries/MS.svg";
import flag_MT from "../../assets/img/countries/MT.svg";
import flag_MU from "../../assets/img/countries/MU.svg";
import flag_MV from "../../assets/img/countries/MV.svg";
import flag_MW from "../../assets/img/countries/MW.svg";
import flag_MX from "../../assets/img/countries/MX.svg";
import flag_MY from "../../assets/img/countries/MY.svg";
import flag_MZ from "../../assets/img/countries/MZ.svg";
import flag_NA from "../../assets/img/countries/NA.svg";
import flag_NE from "../../assets/img/countries/NE.svg";
import flag_NG from "../../assets/img/countries/NG.svg";
import flag_NI from "../../assets/img/countries/NI.svg";
import flag_NL from "../../assets/img/countries/NL.svg";
import flag_NO from "../../assets/img/countries/NO.svg";
import flag_NP from "../../assets/img/countries/NP.svg";
import flag_NR from "../../assets/img/countries/NR.svg";
import flag_NU from "../../assets/img/countries/NU.svg";
import flag_NZ from "../../assets/img/countries/NZ.svg";
import flag_OM from "../../assets/img/countries/OM.svg";
import flag_PA from "../../assets/img/countries/PA.svg";
import flag_PE from "../../assets/img/countries/PE.svg";
import flag_PG from "../../assets/img/countries/PG.svg";
import flag_PH from "../../assets/img/countries/PH.svg";
import flag_PK from "../../assets/img/countries/PK.svg";
import flag_PL from "../../assets/img/countries/PL.svg";
import flag_PM from "../../assets/img/countries/PM.svg";
import flag_PN from "../../assets/img/countries/PN.svg";
import flag_PR from "../../assets/img/countries/PR.svg";
import flag_PS from "../../assets/img/countries/PS.svg";
import flag_PT from "../../assets/img/countries/PT.svg";
import flag_PW from "../../assets/img/countries/PW.svg";
import flag_PY from "../../assets/img/countries/PY.svg";
import flag_QA from "../../assets/img/countries/QA.svg";
import flag_RE from "../../assets/img/countries/RE.svg";
import flag_RO from "../../assets/img/countries/RO.svg";
import flag_RS from "../../assets/img/countries/RS.svg";
import flag_RU from "../../assets/img/countries/RU.svg";
import flag_RW from "../../assets/img/countries/RW.svg";
import flag_SA from "../../assets/img/countries/SA.svg";
import flag_SB from "../../assets/img/countries/SB.svg";
import flag_SC from "../../assets/img/countries/SC.svg";
import flag_SD from "../../assets/img/countries/SD.svg";
import flag_SS from "../../assets/img/countries/SS.svg";
import flag_SE from "../../assets/img/countries/SE.svg";
import flag_SG from "../../assets/img/countries/SG.svg";
import flag_SH from "../../assets/img/countries/SH.svg";
import flag_SI from "../../assets/img/countries/SI.svg";
import flag_SK from "../../assets/img/countries/SK.svg";
import flag_SL from "../../assets/img/countries/SL.svg";
import flag_SM from "../../assets/img/countries/SM.svg";
import flag_SN from "../../assets/img/countries/SN.svg";
import flag_SO from "../../assets/img/countries/SO.svg";
import flag_SR from "../../assets/img/countries/SR.svg";
import flag_ST from "../../assets/img/countries/ST.svg";
import flag_SV from "../../assets/img/countries/SV.svg";
import flag_SY from "../../assets/img/countries/SY.svg";
import flag_SZ from "../../assets/img/countries/SZ.svg";
import flag_TC from "../../assets/img/countries/TC.svg";
import flag_TD from "../../assets/img/countries/TD.svg";
import flag_TF from "../../assets/img/countries/TF.svg";
import flag_TG from "../../assets/img/countries/TG.svg";
import flag_TH from "../../assets/img/countries/TH.svg";
import flag_TJ from "../../assets/img/countries/TJ.svg";
import flag_TK from "../../assets/img/countries/TK.svg";
import flag_TL from "../../assets/img/countries/TL.svg";
import flag_TM from "../../assets/img/countries/TM.svg";
import flag_TN from "../../assets/img/countries/TN.svg";
import flag_TO from "../../assets/img/countries/TO.svg";
import flag_TR from "../../assets/img/countries/TR.svg";
import flag_TT from "../../assets/img/countries/TT.svg";
import flag_TV from "../../assets/img/countries/TV.svg";
import flag_TW from "../../assets/img/countries/TW.svg";
import flag_TZ from "../../assets/img/countries/TZ.svg";
import flag_UA from "../../assets/img/countries/UA.svg";
import flag_UG from "../../assets/img/countries/UG.svg";
import flag_UM from "../../assets/img/countries/UM.svg";
import flag_US from "../../assets/img/countries/US.svg";
import flag_UY from "../../assets/img/countries/UY.svg";
import flag_UZ from "../../assets/img/countries/UZ.svg";
import flag_VA from "../../assets/img/countries/VA.svg";
import flag_VC from "../../assets/img/countries/VC.svg";
import flag_VE from "../../assets/img/countries/VE.svg";
import flag_VG from "../../assets/img/countries/VG.svg";
import flag_VI from "../../assets/img/countries/VI.svg";
import flag_VN from "../../assets/img/countries/VN.svg";
import flag_VU from "../../assets/img/countries/VU.svg";
import flag_WF from "../../assets/img/countries/WF.svg";
import flag_WS from "../../assets/img/countries/WS.svg";
import flag_YE from "../../assets/img/countries/YE.svg";
import flag_YT from "../../assets/img/countries/YT.svg";
import flag_ZA from "../../assets/img/countries/ZA.svg";
import flag_ZM from "../../assets/img/countries/ZM.svg";
import flag_ZW from "../../assets/img/countries/ZW.svg";

// JS Object
const CountryFlags: Record<string, string> = {
	AD: flag_AD,
	AE: flag_AE,
	AF: flag_AF,
	AG: flag_AG,
	AI: flag_AI,
	AL: flag_AL,
	AM: flag_AM,
	AO: flag_AO,
	AQ: flag_AQ,
	AR: flag_AR,
	AS: flag_AS,
	AT: flag_AT,
	AU: flag_AU,
	AZ: flag_AZ,
	BA: flag_BA,
	BB: flag_BB,
	BD: flag_BD,
	BE: flag_BE,
	BF: flag_BF,
	BG: flag_BG,
	BH: flag_BH,
	BI: flag_BI,
	BJ: flag_BJ,
	BM: flag_BM,
	BN: flag_BN,
	BO: flag_BO,
	BQ: flag_BQ,
	BR: flag_BR,
	BS: flag_BS,
	BT: flag_BT,
	BW: flag_BW,
	BY: flag_BY,
	BZ: flag_BZ,
	CA: flag_CA,
	CD: flag_CD,
	CF: flag_CF,
	CG: flag_CG,
	CH: flag_CH,
	CI: flag_CI,
	CK: flag_CK,
	CL: flag_CL,
	CM: flag_CM,
	CN: flag_CN,
	CO: flag_CO,
	CR: flag_CR,
	CU: flag_CU,
	CV: flag_CV,
	CY: flag_CY,
	CZ: flag_CZ,
	DE: flag_DE,
	DJ: flag_DJ,
	DK: flag_DK,
	DM: flag_DM,
	DO: flag_DO,
	DZ: flag_DZ,
	EC: flag_EC,
	EE: flag_EE,
	EG: flag_EG,
	ER: flag_ER,
	ES: flag_ES,
	ET: flag_ET,
	FI: flag_FI,
	FJ: flag_FJ,
	FK: flag_FK,
	FM: flag_FM,
	FO: flag_FO,
	FR: flag_FR,
	GA: flag_GA,
	GB: flag_GB,
	GD: flag_GD,
	GE: flag_GE,
	GF: flag_GF,
	GG: flag_GG,
	GH: flag_GH,
	GI: flag_GI,
	GL: flag_GL,
	GM: flag_GM,
	GN: flag_GN,
	GP: flag_GP,
	GQ: flag_GQ,
	GR: flag_GR,
	GS: flag_GS,
	GT: flag_GT,
	GU: flag_GU,
	GW: flag_GW,
	GY: flag_GY,
	HK: flag_HK,
	HN: flag_HN,
	HR: flag_HR,
	HT: flag_HT,
	HU: flag_HU,
	ID: flag_ID,
	IE: flag_IE,
	IL: flag_IL,
	IM: flag_IM,
	IN: flag_IN,
	IO: flag_IO,
	IQ: flag_IQ,
	IR: flag_IR,
	IS: flag_IS,
	IT: flag_IT,
	JE: flag_JE,
	JM: flag_JM,
	JO: flag_JO,
	JP: flag_JP,
	KE: flag_KE,
	KG: flag_KG,
	KH: flag_KH,
	KI: flag_KI,
	KM: flag_KM,
	KN: flag_KN,
	KP: flag_KP,
	KR: flag_KR,
	KW: flag_KW,
	KY: flag_KY,
	KZ: flag_KZ,
	LA: flag_LA,
	LB: flag_LB,
	LC: flag_LC,
	LI: flag_LI,
	LK: flag_LK,
	LR: flag_LR,
	LS: flag_LS,
	LT: flag_LT,
	LU: flag_LU,
	LV: flag_LV,
	LY: flag_LY,
	MA: flag_MA,
	MC: flag_MC,
	MD: flag_MD,
	ME: flag_ME,
	MG: flag_MG,
	MH: flag_MH,
	MK: flag_MK,
	ML: flag_ML,
	MM: flag_MM,
	MN: flag_MN,
	MO: flag_MO,
	MP: flag_MP,
	MQ: flag_MQ,
	MR: flag_MR,
	MS: flag_MS,
	MT: flag_MT,
	MU: flag_MU,
	MV: flag_MV,
	MW: flag_MW,
	MX: flag_MX,
	MY: flag_MY,
	MZ: flag_MZ,
	NA: flag_NA,
	NE: flag_NE,
	NG: flag_NG,
	NI: flag_NI,
	NL: flag_NL,
	NO: flag_NO,
	NP: flag_NP,
	NR: flag_NR,
	NU: flag_NU,
	NZ: flag_NZ,
	OM: flag_OM,
	PA: flag_PA,
	PE: flag_PE,
	PG: flag_PG,
	PH: flag_PH,
	PK: flag_PK,
	PL: flag_PL,
	PM: flag_PM,
	PN: flag_PN,
	PR: flag_PR,
	PS: flag_PS,
	PT: flag_PT,
	PW: flag_PW,
	PY: flag_PY,
	QA: flag_QA,
	RE: flag_RE,
	RO: flag_RO,
	RS: flag_RS,
	RU: flag_RU,
	RW: flag_RW,
	SA: flag_SA,
	SB: flag_SB,
	SC: flag_SC,
	SD: flag_SD,
	SS: flag_SS,
	SE: flag_SE,
	SG: flag_SG,
	SH: flag_SH,
	SI: flag_SI,
	SK: flag_SK,
	SL: flag_SL,
	SM: flag_SM,
	SN: flag_SN,
	SO: flag_SO,
	SR: flag_SR,
	ST: flag_ST,
	SV: flag_SV,
	SY: flag_SY,
	SZ: flag_SZ,
	TC: flag_TC,
	TD: flag_TD,
	TF: flag_TF,
	TG: flag_TG,
	TH: flag_TH,
	TJ: flag_TJ,
	TK: flag_TK,
	TL: flag_TL,
	TM: flag_TM,
	TN: flag_TN,
	TO: flag_TO,
	TR: flag_TR,
	TT: flag_TT,
	TV: flag_TV,
	TW: flag_TW,
	TZ: flag_TZ,
	UA: flag_UA,
	UG: flag_UG,
	UM: flag_UM,
	US: flag_US,
	UY: flag_UY,
	UZ: flag_UZ,
	VA: flag_VA,
	VC: flag_VC,
	VE: flag_VE,
	VG: flag_VG,
	VI: flag_VI,
	VN: flag_VN,
	VU: flag_VU,
	WF: flag_WF,
	WS: flag_WS,
	YE: flag_YE,
	YT: flag_YT,
	ZA: flag_ZA,
	ZM: flag_ZM,
	ZW: flag_ZW,
};

export default CountryFlags;
