#!/bin/sh

if [ "$(git branch --show-current)" = "master" ]; then
  node_modules/.bin/tsc --noEmit -i --tsBuildInfoFile .tscbuildcache &
  TSC_PID=$!
  #TZ=UTC node_modules/.bin/jest &
  #JEST_PID=$!
  wait "$TSC_PID"
  #wait "$JEST_PID"
else
  echo "Not on master branch, not running hooks"
fi
